ALTER TABLE qr_codes ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE qr_codes ADD COLUMN IF NOT EXISTS is_test BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE qr_codes ADD COLUMN IF NOT EXISTS is_permanent BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE qr_codes SET token = public_token WHERE token IS NULL;
ALTER TABLE qr_codes ALTER COLUMN token SET DEFAULT gen_random_uuid()::text;
ALTER TABLE qr_codes ALTER COLUMN token SET NOT NULL;
