"use client";

import Image from "next/image";
import { FormEvent, useState } from "react";

type Lang = "hy" | "ru" | "en";

const copy = {
  hy: {
    nav: ["Առավելություններ", "Ինչպես է աշխատում", "Գործընկերներին", "Հարցեր"], cta: "Միանալ սպասման ցանկին",
    eyebrow: "ՇՈՒՏՈՎ՝ ՀԱՅԱՍՏԱՆՈՒՄ", title: <>Քո կենդանու կյանքը՝ <span>կազմակերպված։</span></>,
    lead: "Վստահելի խնամք, կարևոր տեղեկություններ և կենդանիների ծառայություններ՝ մեկ պարզ ու հոգատար վայրում։",
    provider: "Ես ծառայություն եմ առաջարկում", trust: ["Անվճար վաղ հասանելիություն", "Շների և կատուների համար", "Հայերեն • Русский • English"],
    problemKicker: "ԱՎԵԼԻ ՔԻՉ ԱՆՀԱՆԳՍՏՈՒԹՅՈՒՆ", problemTitle: "Խնամքը չպետք է մասնատված լինի։",
    problemLead: "BuddyLife-ը հավաքում է այն, ինչ այսօր պահում եք տարբեր չատերում, թղթերում և էջերում։",
    problems: [["Վստահություն", "Գտեք ստուգված մասնագետների և հասկացեք՝ ում եք վստահում ձեր կենդանուն։"], ["Հիշեցումներ", "Պատվաստումները, այցերն ու խնամքի կարևոր օրերը այլևս չեն կորչի։"], ["Մեկ պատմություն", "Առողջության և խնամքի տվյալները պահեք մեկ հասանելի պրոֆիլում։"]],
    featureKicker: "ՄԵԿ ՀՈԳԱՏԱՐ ԷԿՈՀԱՄԱԿԱՐԳ", featureTitle: "Ամեն ինչ, որ պետք է լավ կյանք կազմակերպելու համար։",
    features: [["Կենդանու պրոֆիլ", "Կարևոր տվյալները, փաստաթղթերն ու պատմությունը՝ մեկ վայրում։"], ["Վստահելի ծառայություններ", "Բացահայտեք անասնաբույժներ, խնամք և այլ ծառայություններ՝ սկսած Երևանից։"], ["Խելացի հիշեցումներ", "Ստացեք ճիշտ ժամանակին հիշեցումներ պատվաստումների, այցերի և խնամքի մասին։"], ["Համայնք", "Կիսվեք փորձով և սովորեք Հայաստանի կենդանասերներից։"]],
    howKicker: "ՊԱՐԶ ՍԿԻԶԲ", howTitle: "Երեք քայլ դեպի ավելի հանգիստ խնամք։", steps: [["Ստեղծեք պրոֆիլ", "Ավելացրեք կենդանու հիմնական տվյալները։"], ["Կազմակերպեք խնամքը", "Պահեք պատմությունն ու նշանակեք հիշեցումներ։"], ["Գտեք վստահելի օգնություն", "Բացահայտեք համապատասխան մասնագետներ և ծառայություններ։"]],
    partnerKicker: "ԲԻԶՆԵՍՆԵՐԻ ԵՎ ՄԱՍՆԱԳԵՏՆԵՐԻ ՀԱՄԱՐ", partnerTitle: "Աճեք BuddyLife-ի վաղ գործընկերների հետ։", partnerText: "Կլինիկաները, խնամքի կենտրոնները, հյուրանոցները և մասնագետները կարող են ներկայանալ ճիշտ լսարանին և առաջիններից կառուցել վստահելի պրոֆիլ։", partnerCta: "Դառնալ վաղ գործընկեր",
    waitKicker: "ՎԱՂ ՀԱՍԱՆԵԼԻՈՒԹՅՈՒՆ", waitTitle: "Միացեք BuddyLife-ի առաջին համայնքին։", waitText: "Գրանցվեք՝ նորություններին, վաղ հասանելիությանը և մեկնարկային առաջարկներին առաջինը հասնելու համար։",
    owner: "Կենդանու տեր", business: "Ծառայություն", email: "Էլ․ փոստ", city: "Քաղաք", pet: "Կենդանի", choose: "Ընտրել", dog: "Շուն", cat: "Կատու", both: "Երկուսն էլ", consent: "Համաձայն եմ ստանալ BuddyLife-ի մեկնարկի նորությունները։", submit: "Պահպանել իմ տեղը", success: "Շնորհակալություն։ Դուք սպասման ցանկում եք 💜",
    faqKicker: "ՀԱՐՑԵՐ", faqTitle: "Ամենակարևորը՝ մեկնարկից առաջ։", faqs: [["Ե՞րբ է գործարկվելու BuddyLife-ը։", "Առաջին տարբերակը նախատեսվում է առաջիկա 2–3 ամսում։ Սպասման ցանկի անդամները նորությունները կստանան առաջինը։"], ["Որտե՞ղ է հասանելի լինելու։", "Սկսում ենք Հայաստանից՝ առաջին փուլում կենտրոնանալով Երևանի վրա, ապա ընդլայնվելու ենք։"], ["Արդյո՞ք ծառայությունների ամրագրումն արդեն հասանելի է։", "Ոչ դեռ։ Մենք փուլ առ փուլ ստուգում ենք գործընկերներին և կբացենք հնարավորությունները, երբ դրանք պատրաստ լինեն։"], ["Անվճա՞ր է միանալը։", "Այո, սպասման ցանկին և վաղ հասանելիության համայնքին միանալն անվճար է։"]],
    footer: "Ձեր կենդանին։ Ձեր ընտանիքը։ Մեր հոգատարությունը։", privacy: "© 2026 BuddyLife Armenia"
  },
  ru: {
    nav: ["Преимущества", "Как это работает", "Партнёрам", "Вопросы"], cta: "В лист ожидания", eyebrow: "СКОРО В АРМЕНИИ", title: <>Жизнь питомца — <span>организована.</span></>, lead: "Надёжная забота, важные данные и услуги для питомцев — в одном простом и тёплом пространстве.", provider: "Я предлагаю услуги", trust: ["Бесплатный ранний доступ", "Для собак и кошек", "Հայերեն • Русский • English"],
    problemKicker: "МЕНЬШЕ ТРЕВОГ", problemTitle: "Забота не должна быть разбросана.", problemLead: "BuddyLife объединяет то, что сегодня хранится в чатах, бумагах и разных сервисах.", problems: [["Доверие", "Находите проверенных специалистов и понимайте, кому доверяете питомца."], ["Напоминания", "Вакцины, визиты и важные даты больше не потеряются."], ["Единая история", "Храните данные о здоровье и уходе в одном доступном профиле."]],
    featureKicker: "ЕДИНАЯ ЭКОСИСТЕМА", featureTitle: "Всё для хорошо организованной жизни питомца.", features: [["Профиль питомца", "Данные, документы и история в одном месте."], ["Надёжные услуги", "Ветеринары, уход и другие услуги — начиная с Еревана."], ["Умные напоминания", "Важные уведомления о вакцинах, визитах и уходе."], ["Сообщество", "Делитесь опытом с владельцами питомцев в Армении."]],
    howKicker: "ПРОСТОЙ СТАРТ", howTitle: "Три шага к спокойной заботе.", steps: [["Создайте профиль", "Добавьте основную информацию о питомце."], ["Организуйте уход", "Сохраните историю и настройте напоминания."], ["Найдите помощь", "Откройте подходящих специалистов и услуги."]], partnerKicker: "ДЛЯ БИЗНЕСА", partnerTitle: "Растите вместе с ранними партнёрами BuddyLife.", partnerText: "Клиники, грумеры, отели и специалисты смогут предстать перед целевой аудиторией и первыми создать доверенный профиль.", partnerCta: "Стать ранним партнёром",
    waitKicker: "РАННИЙ ДОСТУП", waitTitle: "Присоединяйтесь к первому сообществу BuddyLife.", waitText: "Зарегистрируйтесь, чтобы первыми узнать о запуске и получить ранний доступ.", owner: "Владелец", business: "Бизнес", email: "Эл. почта", city: "Город", pet: "Питомец", choose: "Выбрать", dog: "Собака", cat: "Кошка", both: "Оба", consent: "Я согласен получать новости о запуске BuddyLife.", submit: "Сохранить место", success: "Спасибо. Вы в листе ожидания 💜",
    faqKicker: "ВОПРОСЫ", faqTitle: "Главное перед запуском.", faqs: [["Когда запустится BuddyLife?", "Первая версия планируется в ближайшие 2–3 месяца."], ["Где будет доступен сервис?", "Начинаем с Армении и в первую очередь с Еревана."], ["Бронирование уже доступно?", "Пока нет. Мы проверяем партнёров и откроем функции, когда они будут готовы."], ["Присоединиться можно бесплатно?", "Да, лист ожидания и раннее сообщество бесплатны."]], footer: "Ваш питомец. Ваша семья. Наша забота.", privacy: "© 2026 BuddyLife Armenia"
  },
  en: {
    nav: ["Benefits", "How it works", "For providers", "FAQ"], cta: "Join the waitlist", eyebrow: "COMING SOON TO ARMENIA", title: <>Your pet’s life, <span>organized.</span></>, lead: "Trusted care, essential records and pet services in one simple, caring place.", provider: "I provide pet services", trust: ["Free early access", "For dogs and cats", "Հայերեն • Русский • English"],
    problemKicker: "LESS WORRY", problemTitle: "Pet care shouldn’t feel fragmented.", problemLead: "BuddyLife brings together what owners currently keep across chats, papers and separate services.", problems: [["Trust", "Find vetted professionals and understand who you are trusting with your pet."], ["Reminders", "Vaccinations, appointments and important care dates will no longer get lost."], ["One history", "Keep health and care information in one accessible pet profile."]],
    featureKicker: "ONE CARING ECOSYSTEM", featureTitle: "Everything you need for a well-organized pet life.", features: [["Pet profile", "Important details, documents and history in one place."], ["Trusted services", "Discover vets, grooming and more—starting in Yerevan."], ["Smart reminders", "Timely nudges for vaccinations, appointments and care."], ["Community", "Share experience with pet parents across Armenia."]],
    howKicker: "A SIMPLE START", howTitle: "Three steps to calmer pet care.", steps: [["Create a profile", "Add your pet’s essential information."], ["Organize care", "Save the history and schedule reminders."], ["Find trusted help", "Discover relevant professionals and services."]], partnerKicker: "FOR PET BUSINESSES", partnerTitle: "Grow with BuddyLife’s early partners.", partnerText: "Clinics, groomers, hotels and specialists can reach the right audience and be among the first to build a trusted profile.", partnerCta: "Become an early partner",
    waitKicker: "EARLY ACCESS", waitTitle: "Join BuddyLife’s first community.", waitText: "Sign up to hear launch news first, access the early release and receive founding offers.", owner: "Pet parent", business: "Provider", email: "Email", city: "City", pet: "Pet", choose: "Choose", dog: "Dog", cat: "Cat", both: "Both", consent: "I agree to receive BuddyLife launch updates.", submit: "Save my place", success: "Thank you. You’re on the waitlist 💜",
    faqKicker: "FAQ", faqTitle: "What matters before launch.", faqs: [["When will BuddyLife launch?", "The first release is planned in the next 2–3 months."], ["Where will it be available?", "We are starting in Armenia, focusing first on Yerevan."], ["Can I book services already?", "Not yet. We are validating partners and will open features when they are ready."], ["Is it free to join?", "Yes. Joining the waitlist and early community is free."]], footer: "Your pet. Your family. Our care.", privacy: "© 2026 BuddyLife Armenia"
  }
};

export default function Home() {
  const [lang, setLang] = useState<Lang>("hy"); const [role, setRole] = useState("owner"); const [sent, setSent] = useState(false); const t = copy[lang];
  const submit = (e: FormEvent) => { e.preventDefault(); setSent(true); };
  return <main>
    <header className="nav shell"><a className="brand" href="#top"><Image src="/buddylife-logo.png" alt="BuddyLife" width={132} height={132}/></a><nav className="navLinks"><a href="#benefits">{t.nav[0]}</a><a href="#how">{t.nav[1]}</a><a href="#providers">{t.nav[2]}</a><a href="#faq">{t.nav[3]}</a></nav><div className="navRight"><div className="languages">{(["hy","ru","en"] as Lang[]).map(x=><button key={x} onClick={()=>setLang(x)} className={lang===x?"active":""}>{x.toUpperCase()}</button>)}</div><a className="button buttonSmall" href="#waitlist">{t.cta}</a></div></header>
    <section className="hero shell" id="top"><div className="heroCopy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="lead">{t.lead}</p><div className="heroActions"><a className="button" href="#waitlist">{t.cta}</a><a className="textLink" href="#providers">{t.provider} <span>→</span></a></div><div className="trustRow">{t.trust.map(x=><span key={x}>{x}</span>)}</div></div><div className="heroVisual"><Image src="/hero-pets.jpg" alt="Dog and cat at home" fill priority sizes="(max-width: 900px) 100vw, 45vw"/><div className="careCard"><span className="careIcon">♥</span><div><strong>BuddyLife Care</strong><small>{t.features[2][0]} · {t.features[1][0]}</small></div></div></div></section>
    <section className="section problem" id="benefits"><div className="shell"><div className="sectionIntro"><p className="eyebrow">{t.problemKicker}</p><h2>{t.problemTitle}</h2><p>{t.problemLead}</p></div><div className="problemGrid">{t.problems.map((x,i)=><article className="problemCard" key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
    <section className="section features"><div className="shell featureLayout"><div className="phoneMock"><div className="phoneTop"><Image src="/buddylife-logo.png" alt="" width={80} height={80}/><span>•••</span></div><div className="petMini"><span>🐶</span><div><strong>Max</strong><small>Golden Retriever · 3 years</small></div></div><div className="reminder"><small>{t.features[2][0]}</small><strong>Vaccination · 12 Sep</strong></div><div className="serviceMini"><span>✦</span><div><strong>{t.features[1][0]}</strong><small>4.9 ★ · Yerevan</small></div></div></div><div className="featureCopy"><p className="eyebrow">{t.featureKicker}</p><h2>{t.featureTitle}</h2><div className="featureGrid">{t.features.map((x,i)=><article className="featureCard" key={x[0]}><span className="featureIcon">{["♡","⌖","◷","✦"][i]}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></div></div></section>
    <section className="section how" id="how"><div className="shell"><div className="sectionIntro centered"><p className="eyebrow">{t.howKicker}</p><h2>{t.howTitle}</h2></div><div className="steps">{t.steps.map((x,i)=><article className="step" key={x[0]}><span>{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
    <section className="section providers" id="providers"><div className="shell providerPanel"><div><p className="eyebrow light">{t.partnerKicker}</p><h2>{t.partnerTitle}</h2><p>{t.partnerText}</p></div><a href="#waitlist" onClick={()=>setRole("business")} className="button whiteButton">{t.partnerCta}</a></div></section>
    <section className="section waitlist" id="waitlist"><div className="shell waitGrid"><div><p className="eyebrow">{t.waitKicker}</p><h2>{t.waitTitle}</h2><p className="sectionLead">{t.waitText}</p><div className="socialLinks"><a href="https://www.instagram.com/buddylifearmenia/">Instagram ↗</a><a href="https://www.facebook.com/profile.php?id=61593562114437">Facebook ↗</a></div></div><form className="waitForm" onSubmit={submit}><div className="roleTabs"><button type="button" className={role==="owner"?"active":""} onClick={()=>setRole("owner")}>{t.owner}</button><button type="button" className={role==="business"?"active":""} onClick={()=>setRole("business")}>{t.business}</button></div><label>{t.email}<input required type="email" placeholder="name@email.com"/></label><div className="formRow"><label>{t.city}<input required placeholder="Yerevan"/></label><label>{t.pet}<select required defaultValue=""><option value="" disabled>{t.choose}</option><option>{t.dog}</option><option>{t.cat}</option><option>{t.both}</option></select></label></div><label className="check"><input required type="checkbox"/><span>{t.consent}</span></label><button className="button submit">{t.submit}</button>{sent&&<p className="success">{t.success}</p>}</form></div></section>
    <section className="section faq" id="faq"><div className="shell faqLayout"><div><p className="eyebrow">{t.faqKicker}</p><h2>{t.faqTitle}</h2></div><div className="faqList">{t.faqs.map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></div></section>
    <footer><div className="shell footerInner"><div className="footerBrand"><Image src="/buddylife-logo.png" alt="BuddyLife" width={112} height={112}/><p>{t.footer}</p></div><div><a href="https://www.instagram.com/buddylifearmenia/">Instagram</a><a href="https://www.facebook.com/profile.php?id=61593562114437">Facebook</a><small>{t.privacy}</small></div></div></footer>
  </main>;
}
